apiVersion: v1
kind: Service
metadata:
  name: crypto-recommendation-service
spec:
  selector:
    app: crypto-recommendation
  ports:
    - protocol: TCP
      port: 8080       # Port exposed by service
      targetPort: 8080 # Port exposed by container
  type: NodePort       # For local access
